import { type EngineeringProjectModel } from "../../schema/project-model";

/**
 * Compiles the firmware config into a production-grade C++ script.
 */
export function generateFirmware(model: EngineeringProjectModel): string {
  const fw = model.firmware;
  const lines: string[] = [];

  lines.push(`// Firmware generated for ${model.metadata.title}`);
  lines.push(`// Target Platform: ${fw.platform}`);
  lines.push("// Generated by CircuitMind AI (Fayek Ahanaf)");
  lines.push("");

  // Libraries
  if (fw.libraries && fw.libraries.length > 0) {
    fw.libraries.forEach((lib) => {
      if (lib.startsWith("<") || lib.startsWith('"')) {
        lines.push(`#include ${lib}`);
      } else {
        lines.push(`#include <${lib}>`);
      }
    });
    lines.push("");
  }

  // Safety Warnings / Checks in header comments
  if (fw.safetyChecks && fw.safetyChecks.length > 0) {
    lines.push("/**");
    lines.push(" * SAFETY CHECKS:");
    fw.safetyChecks.forEach((check) => {
      lines.push(` * - ${check}`);
    });
    lines.push(" */");
    lines.push("");
  }

  // Constants
  if (fw.constants && Object.keys(fw.constants).length > 0) {
    lines.push("// Constant definitions");
    Object.entries(fw.constants).forEach(([k, v]) => {
      lines.push(`#define ${k} ${v}`);
    });
    lines.push("");
  }

  // Pin Definitions
  if (fw.pinDefinitions && Object.keys(fw.pinDefinitions).length > 0) {
    lines.push("// Pin configurations");
    Object.entries(fw.pinDefinitions).forEach(([k, v]) => {
      lines.push(`const int ${k} = ${v};`);
    });
    lines.push("");
  }

  // Setup Function
  lines.push("void setup() {");
  lines.push("  Serial.begin(115200);");
  if (fw.setupCode) {
    const indented = fw.setupCode.split("\n").map(l => "  " + l).join("\n");
    lines.push(indented);
  }
  lines.push("}");
  lines.push("");

  // Loop Function
  lines.push("void loop() {");
  if (fw.loopCode) {
    const indented = fw.loopCode.split("\n").map(l => "  " + l).join("\n");
    lines.push(indented);
  }
  lines.push("}");
  lines.push("");

  // Custom Helper Functions
  if (fw.customFunctions && fw.customFunctions.length > 0) {
    lines.push("// User custom functions");
    fw.customFunctions.forEach((fn) => {
      lines.push(`${fn.signature} {`);
      lines.push(fn.code.split("\n").map(l => "  " + l).join("\n"));
      lines.push("}");
      lines.push("");
    });
  }

  return lines.join("\n");
}
