/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard.index'
import { Route as DashboardTemplatesRouteImport } from './routes/dashboard.templates'
import { Route as DashboardSettingsRouteImport } from './routes/dashboard.settings'
import { Route as DashboardProjectsRouteImport } from './routes/dashboard.projects'
import { Route as DashboardProfileRouteImport } from './routes/dashboard.profile'
import { Route as DashboardOptimizerRouteImport } from './routes/dashboard.optimizer'
import { Route as DashboardHistoryRouteImport } from './routes/dashboard.history'
import { Route as DashboardGeneratorRouteImport } from './routes/dashboard.generator'
import { Route as DashboardComponentsRouteImport } from './routes/dashboard.components'
import { Route as DashboardChatRouteImport } from './routes/dashboard.chat'
import { Route as DashboardTemplatesIdRouteImport } from './routes/dashboard.templates.$id'
import { Route as DashboardComponentsIdRouteImport } from './routes/dashboard.components.$id'

const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardTemplatesRoute = DashboardTemplatesRouteImport.update({
  id: '/templates',
  path: '/templates',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardSettingsRoute = DashboardSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardProjectsRoute = DashboardProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardProfileRoute = DashboardProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardOptimizerRoute = DashboardOptimizerRouteImport.update({
  id: '/optimizer',
  path: '/optimizer',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardHistoryRoute = DashboardHistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardGeneratorRoute = DashboardGeneratorRouteImport.update({
  id: '/generator',
  path: '/generator',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardComponentsRoute = DashboardComponentsRouteImport.update({
  id: '/components',
  path: '/components',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardChatRoute = DashboardChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardTemplatesIdRoute = DashboardTemplatesIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => DashboardTemplatesRoute,
} as any)
const DashboardComponentsIdRoute = DashboardComponentsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => DashboardComponentsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/dashboard/chat': typeof DashboardChatRoute
  '/dashboard/components': typeof DashboardComponentsRouteWithChildren
  '/dashboard/generator': typeof DashboardGeneratorRoute
  '/dashboard/history': typeof DashboardHistoryRoute
  '/dashboard/optimizer': typeof DashboardOptimizerRoute
  '/dashboard/profile': typeof DashboardProfileRoute
  '/dashboard/projects': typeof DashboardProjectsRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/dashboard/templates': typeof DashboardTemplatesRouteWithChildren
  '/dashboard/': typeof DashboardIndexRoute
  '/dashboard/components/$id': typeof DashboardComponentsIdRoute
  '/dashboard/templates/$id': typeof DashboardTemplatesIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/dashboard/chat': typeof DashboardChatRoute
  '/dashboard/components': typeof DashboardComponentsRouteWithChildren
  '/dashboard/generator': typeof DashboardGeneratorRoute
  '/dashboard/history': typeof DashboardHistoryRoute
  '/dashboard/optimizer': typeof DashboardOptimizerRoute
  '/dashboard/profile': typeof DashboardProfileRoute
  '/dashboard/projects': typeof DashboardProjectsRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/dashboard/templates': typeof DashboardTemplatesRouteWithChildren
  '/dashboard': typeof DashboardIndexRoute
  '/dashboard/components/$id': typeof DashboardComponentsIdRoute
  '/dashboard/templates/$id': typeof DashboardTemplatesIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/dashboard/chat': typeof DashboardChatRoute
  '/dashboard/components': typeof DashboardComponentsRouteWithChildren
  '/dashboard/generator': typeof DashboardGeneratorRoute
  '/dashboard/history': typeof DashboardHistoryRoute
  '/dashboard/optimizer': typeof DashboardOptimizerRoute
  '/dashboard/profile': typeof DashboardProfileRoute
  '/dashboard/projects': typeof DashboardProjectsRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/dashboard/templates': typeof DashboardTemplatesRouteWithChildren
  '/dashboard/': typeof DashboardIndexRoute
  '/dashboard/components/$id': typeof DashboardComponentsIdRoute
  '/dashboard/templates/$id': typeof DashboardTemplatesIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/auth'
    | '/dashboard'
    | '/dashboard/chat'
    | '/dashboard/components'
    | '/dashboard/generator'
    | '/dashboard/history'
    | '/dashboard/optimizer'
    | '/dashboard/profile'
    | '/dashboard/projects'
    | '/dashboard/settings'
    | '/dashboard/templates'
    | '/dashboard/'
    | '/dashboard/components/$id'
    | '/dashboard/templates/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/auth'
    | '/dashboard/chat'
    | '/dashboard/components'
    | '/dashboard/generator'
    | '/dashboard/history'
    | '/dashboard/optimizer'
    | '/dashboard/profile'
    | '/dashboard/projects'
    | '/dashboard/settings'
    | '/dashboard/templates'
    | '/dashboard'
    | '/dashboard/components/$id'
    | '/dashboard/templates/$id'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/auth'
    | '/dashboard'
    | '/dashboard/chat'
    | '/dashboard/components'
    | '/dashboard/generator'
    | '/dashboard/history'
    | '/dashboard/optimizer'
    | '/dashboard/profile'
    | '/dashboard/projects'
    | '/dashboard/settings'
    | '/dashboard/templates'
    | '/dashboard/'
    | '/dashboard/components/$id'
    | '/dashboard/templates/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AuthRoute: typeof AuthRoute
  DashboardRoute: typeof DashboardRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/templates': {
      id: '/dashboard/templates'
      path: '/templates'
      fullPath: '/dashboard/templates'
      preLoaderRoute: typeof DashboardTemplatesRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/settings': {
      id: '/dashboard/settings'
      path: '/settings'
      fullPath: '/dashboard/settings'
      preLoaderRoute: typeof DashboardSettingsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/projects': {
      id: '/dashboard/projects'
      path: '/projects'
      fullPath: '/dashboard/projects'
      preLoaderRoute: typeof DashboardProjectsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/profile': {
      id: '/dashboard/profile'
      path: '/profile'
      fullPath: '/dashboard/profile'
      preLoaderRoute: typeof DashboardProfileRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/optimizer': {
      id: '/dashboard/optimizer'
      path: '/optimizer'
      fullPath: '/dashboard/optimizer'
      preLoaderRoute: typeof DashboardOptimizerRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/history': {
      id: '/dashboard/history'
      path: '/history'
      fullPath: '/dashboard/history'
      preLoaderRoute: typeof DashboardHistoryRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/generator': {
      id: '/dashboard/generator'
      path: '/generator'
      fullPath: '/dashboard/generator'
      preLoaderRoute: typeof DashboardGeneratorRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/components': {
      id: '/dashboard/components'
      path: '/components'
      fullPath: '/dashboard/components'
      preLoaderRoute: typeof DashboardComponentsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/chat': {
      id: '/dashboard/chat'
      path: '/chat'
      fullPath: '/dashboard/chat'
      preLoaderRoute: typeof DashboardChatRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/templates/$id': {
      id: '/dashboard/templates/$id'
      path: '/$id'
      fullPath: '/dashboard/templates/$id'
      preLoaderRoute: typeof DashboardTemplatesIdRouteImport
      parentRoute: typeof DashboardTemplatesRoute
    }
    '/dashboard/components/$id': {
      id: '/dashboard/components/$id'
      path: '/$id'
      fullPath: '/dashboard/components/$id'
      preLoaderRoute: typeof DashboardComponentsIdRouteImport
      parentRoute: typeof DashboardComponentsRoute
    }
  }
}

interface DashboardComponentsRouteChildren {
  DashboardComponentsIdRoute: typeof DashboardComponentsIdRoute
}

const DashboardComponentsRouteChildren: DashboardComponentsRouteChildren = {
  DashboardComponentsIdRoute: DashboardComponentsIdRoute,
}

const DashboardComponentsRouteWithChildren =
  DashboardComponentsRoute._addFileChildren(DashboardComponentsRouteChildren)

interface DashboardTemplatesRouteChildren {
  DashboardTemplatesIdRoute: typeof DashboardTemplatesIdRoute
}

const DashboardTemplatesRouteChildren: DashboardTemplatesRouteChildren = {
  DashboardTemplatesIdRoute: DashboardTemplatesIdRoute,
}

const DashboardTemplatesRouteWithChildren =
  DashboardTemplatesRoute._addFileChildren(DashboardTemplatesRouteChildren)

interface DashboardRouteChildren {
  DashboardChatRoute: typeof DashboardChatRoute
  DashboardComponentsRoute: typeof DashboardComponentsRouteWithChildren
  DashboardGeneratorRoute: typeof DashboardGeneratorRoute
  DashboardHistoryRoute: typeof DashboardHistoryRoute
  DashboardOptimizerRoute: typeof DashboardOptimizerRoute
  DashboardProfileRoute: typeof DashboardProfileRoute
  DashboardProjectsRoute: typeof DashboardProjectsRoute
  DashboardSettingsRoute: typeof DashboardSettingsRoute
  DashboardTemplatesRoute: typeof DashboardTemplatesRouteWithChildren
  DashboardIndexRoute: typeof DashboardIndexRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardChatRoute: DashboardChatRoute,
  DashboardComponentsRoute: DashboardComponentsRouteWithChildren,
  DashboardGeneratorRoute: DashboardGeneratorRoute,
  DashboardHistoryRoute: DashboardHistoryRoute,
  DashboardOptimizerRoute: DashboardOptimizerRoute,
  DashboardProfileRoute: DashboardProfileRoute,
  DashboardProjectsRoute: DashboardProjectsRoute,
  DashboardSettingsRoute: DashboardSettingsRoute,
  DashboardTemplatesRoute: DashboardTemplatesRouteWithChildren,
  DashboardIndexRoute: DashboardIndexRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AuthRoute: AuthRoute,
  DashboardRoute: DashboardRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
